/** Generated by scripts/build-craft-bundles.mjs — ảnh gallery lưu tại public/images/crafts/<slug>/ */
import type { GoogleSitesCraftBundle } from "@/data/google-sites-crafts/types";

export const dengALuoiCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Nghề dệt Dèng A Lưới — Làng nghề Huế",
  "metaDescription": "Nghề dệt Dèng của người Tà Ôi ở A Lưới: di sản phi vật thể quốc gia, quy trình và ý nghĩa văn hóa.",
  "categoryEyebrow": "Dệt thổ cẩm vùng cao",
  "heroTitle": "Nghề dệt Dèng A Lưới",
  "heroTagline": "Hoa văn dệt thổ cẩm Tà Ôi — di sản phi vật thể quốc gia.",
  "introCardParagraphs": [
    "Dèng A Lưới gắn với đời sống cộng đồng dân tộc thiểu số ở vùng núi phía Tây Huế, nổi bật với kỹ thuật dệt tay và trang trí hạt cườm đặc trưng."
  ],
  "heroImage": "/images/villages/det_deng_a_luoi.jpg",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề dệt Dèng là nghề thủ công truyền thống của đồng bào các dân tộc Tà Ôi, Pa Kô, Vân Kiều ở khu vực các xã A Lưới, thành phố Huế. Nghề này được phát triển chủ yếu ở các xã như A Hư­a, A Đớt, xã A Roàng và thị trấn A Lưới, tạo nên những làng nghề truyền thống gắn với văn hoá thổ cẩm của vùng cao Tây Trường Sơn."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Dệt Dèng là một nghề truyền thống đã tồn tại hàng trăm năm, được đồng bào Tà Ôi cùng các dân tộc bản địa khác gìn giữ và truyền từ thế hệ này sang thế hệ khác. Nghề dệt không chỉ để đáp ứng nhu cầu sinh hoạt hàng ngày mà còn gắn với các phong tục, nghi lễ văn hoá như lễ cưới hỏi, lễ hội cộng đồng.",
            "Năm 2016, Bộ Văn hoá, Thể thao và Du lịch đã chính thức công nhận nghề dệt Dèng của người Tà Ôi ở A Lưới là Di sản văn hoá phi vật thể quốc gia theo Quyết định số 4036/QĐ-BVHTTDL, đánh dấu giá trị văn hoá – lịch sử sâu sắc và tầm quan trọng trong kho tàng văn hoá dân tộc Việt Nam."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Nguyên liệu",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Bông được trồng, phơi khô, bóc tách lấy sợi."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Sợi vải được quay từ bông sau khi cán, vấn, giăng sợi."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Màu sắc được nhuộm từ lá, vỏ, củ, rễ cây tự nhiên lấy từ núi rừng."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Gam màu truyền thống là đen, đỏ, trắng và đôi khi các màu xanh, vàng."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Chuẩn bị nguyên liệu: Bông được phơi, tách, kéo sợi và nhuộm bằng nguyên liệu thiên nhiên."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Giăng khung dệt: Sợi đực, sợi cái được giăng lên khung dệt truyền thống."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Dệt vải: Người thợ dệt sử dụng khung dệt tay, kết hợp thao tác chuyên nghiệp để tạo nên nền Dèng."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Trang trí hoa văn: Những hạt cườm, quả rừng, lục lạc… được đính thủ công trên nền vải để tạo họa tiết động, thực vật, thiên nhiên, đồ vật – đặc trưng văn hoá Tà Ôi."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Hoàn thiện sản phẩm: Kiểm tra độ bền, hoa văn, màu sắc trước khi đưa ra thị trường."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Đặc trưng của Dèng là việc đính hạt cườm thủ công trên nền vải, khác biệt rõ rệt với nhiều loại thổ cẩm khác chỉ dùng chỉ màu để tạo hoa văn."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "subsections": [
        {
          "title": "a) Văn hoá – du lịch",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Dệt Dèng gắn liền với văn hoá truyền thống, thu hút du khách đến thăm làng nghề, trải nghiệm dệt Dèng, học kỹ thuật dệt và mua sản phẩm làm quà lưu niệm."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Giá trị thương mại:"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Sản phẩm Dèng đã được giới thiệu rộng rãi qua Festival Nghề truyền thống Huế, nhiều hội chợ – triển lãm, và xuất hiện trong các bộ sưu tập thời trang ứng dụng trên áo dài, túi xách, giày dép, mũ nón… làm tăng giá trị thương mại và thu nhập cho người thợ."
              ]
            }
          ]
        },
        {
          "title": "b) Hợp tác xã và thương hiệu",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Ngày 12/3/2019, Cục Sở hữu trí tuệ đã chứng nhận “A Lưới Dèng” là nhãn hiệu tập thể do Hội Liên hiệp Phụ nữ huyện A Lưới làm chủ chứng nhận, tạo điều kiện quảng bá sản phẩm và phát triển kinh tế – xã hội bền vững."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Một trong những nghệ nhân nổi bật trong việc bảo tồn và phát triển nghề dệt Dèng là bà Mai Thị Hợp – người đã nhiều năm gắn bó với nghề, đưa sản phẩm Dèng ra phục vụ du khách trong nước và quốc tế.",
            "Bà Hợp đã tham gia trình diễn nghề ở các nước như Nhật Bản, Pháp và nhiều sân chơi quốc tế khác; đóng góp vào việc tạo công ăn việc làm cho phụ nữ dân tộc thiểu số, góp phần xóa đói giảm nghèo.",
            "Nhiều nghệ nhân khác ở các làng nghề Dèng A Hừa, A Đớt… cũng đang nỗ lực duy trì và phát triển nghề truyền thống này."
          ]
        }
      ]
    },
    {
      "title": "6. Tiềm năng – Ý nghĩa văn hoá và xã hội",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Dệt Dèng không chỉ là sản phẩm thủ công phục vụ đời sống mà chứa đựng giá trị văn hoá sâu sắc, phản ánh bản sắc người Tà Ôi trong lễ cưới hỏi, nghi lễ cộng đồng, và đời sống tâm linh. Trong văn hoá truyền thống, người phụ nữ đóng vai trò chủ đạo trong việc truyền nghề cho thế hệ sau, và việc dệt Dèng còn được xem là thước đo sự khéo léo, chăm chỉ, tận tâm trong cộng đồng.",
            "Dệt Dèng tạo thêm thu nhập cho bà con, góp phần ổn định kinh tế, giảm nghèo và thúc đẩy phát triển du lịch cộng đồng ở vùng cao A Lưới.",
            "Website Huế Craft Village 4.0",
            "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí",
            "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi",
            "🏫 Trung tâm GDNN-GDTX khu vực 2",
            "Google Sites",
            "Report abuse",
            "Page details",
            "Page updated",
            "Google Sites",
            "Report abuse"
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/det_deng_a_luoi.jpg",
      "alt": "Nghề dệt Dèng A Lưới — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Huyện A Lưới, Thừa Thiên Huế",
  "youtubeEmbeds": [],
  "villageSlug": "deng-a-luoi"
};
export const gomPhuocTichCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Làng gốm Phước Tích — Làng nghề Huế",
  "metaDescription": "Làng gốm Phước Tích: vị trí, lịch sử, sản phẩm, quy trình nung lò và tiềm năng du lịch.",
  "categoryEyebrow": "Gốm truyền thống",
  "heroTitle": "Nghề làm gốm Phước Tích",
  "heroTagline": "Đất nung kể chuyện thời gian bên dòng Ô Lâu.",
  "introCardParagraphs": [
    "Phước Tích gìn giữ lò gốm cổ với quy trình nhào đất, xoay bàn và nung củi, tạo nên chất gốm mộc mạc nhưng bền chắc."
  ],
  "heroImage": "/images/villages/gom-phuoc-tich.png",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Làng gốm Phước Tích nằm trong thôn Phước Phú, phường Phong Dinh (trước đây là xã Phong Hòa, huyện Phong Điền, tỉnh Thừa Thiên Huế) , nằm bên bờ sông Ô Lâu hiền hòa, cách trung tâm TP. Huế khoảng 40 km về phía Bắc. Đây là một làng cổ nổi tiếng với nghề gốm truyền thống và hệ thống nhà cổ kiểu ba gian hai chái đặc trưng của miền Trung."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Làng Phước Tích được thành lập từ khoảng năm 1470 dưới thời vua Lê Thánh Tông, và sau đó được đặt tên Phước Tích trong thời Nguyễn. Nghề làm gốm đã xuất hiện hơn 500 năm tại đây, trở thành nghề chủ đạo của dân làng và gắn liền với đời sống sinh hoạt vùng kinh thành Huế.",
            "Trong quá khứ, làng có tới 12 cửa lò gốm hoạt động liên tục, sản xuất đồ gốm cung cấp cho cả vùng miền Trung và trở thành một trung tâm gốm nổi tiếng. Sản phẩm gốm Phước Tích từng được vua Nguyễn yêu thích và gọi là gốm tiến vua vì các sản phẩm như om nấu cơm cho vua.",
            "Tuy nhiên, nghề gốm ở đây có thời kỳ suy giảm mạnh vào khoảng cuối thập niên 1980 và đầu thập niên 1990, khiến các lò gốm bị tắt. Những năm gần đây, qua các Festival Huế từ 2006, nghề này dần được phục hồi và trở thành điểm du lịch văn hoá nổi bật của tỉnh."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Sản phẩm tiêu biểu",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Gốm Phước Tích gồm nhiều sản phẩm truyền thống phục vụ đời sống như:"
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Om nấu cơm, chậu, niêu, âm, tộ, cối tiêu, bình vôi, chum, ghè, lọ hoa…"
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Với màu đất tự nhiên, thô mộc, sản phẩm không tráng men nhưng vững chắc, bền, chịu nhiệt tốt và đẹp mắt."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình làm gốm",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Chuẩn bị đất sét: Đất sét lấy từ bờ sông Ô Lâu được nhào kỹ cho dẻo."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Tạo hình: Nghệ nhân nặn gốm bằng tay hoặc trên bàn xoay theo khuôn dáng truyền thống."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Phơi khô tự nhiên: Sản phẩm để khô dưới nắng để loại bỏ ẩm trước khi nung."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Nung trong lò truyền thống: Gốm được nung ở nhiệt độ cao liên tục với lửa đỏ rực, giúp đất sét trở nên cứng chắc và có màu đặc trưng."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Hoàn thiện: Sản phẩm sau khi ra lò có màu đất nâu đỏ tự nhiên, bề mặt mịn và rất bền."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Các loại lò truyền thống như “lò ếch” vẫn còn được sử dụng để tạo nhiệt độ và màu sắc đặc trưng cho sản phẩm."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "subsections": [
        {
          "title": "a) Du lịch trải nghiệm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Nghề gốm Phước Tích hiện kết hợp với du lịch văn hoá làng nghề rất hiệu quả. Du khách không chỉ tham quan cảnh làng cổ, lò gốm, nhà rường cổ mà còn được xem trực tiếp quy trình làm gốm và tự tay trải nghiệm làm sản phẩm."
              ]
            }
          ]
        },
        {
          "title": "b) Quảng bá văn hoá & thương mại",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Sản phẩm gốm Phước Tích được bán trong nước và quốc tế, đồng thời giới thiệu rộng rãi trong các kỳ Festival Huế và hội chợ nghề truyền thống. Phong cách sản phẩm truyền thống kết hợp với sáng tạo thiết kế mới có tiềm năng phát triển thành sản phẩm nghệ thuật và du lịch cao cấp."
              ]
            }
          ]
        },
        {
          "title": "c) Bảo tồn và phục hồi nghề",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Giới chức và cộng đồng đã có nhiều nỗ lực hồi sinh nghề gốm truyền thống, kết hợp quảng bá nghệ thuật và kiến trúc làng cổ, tạo thêm nguồn thu từ lữ hành và dịch vụ địa phương."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Trong các báo cáo và bài viết, làng gốm Phước Tích có những nghệ nhân tâm huyết giữ nghề và truyền dạy cho thế hệ sau. Nghệ nhân Lương Thanh Hiển được nhắc đến như một người đang tập trung gìn giữ và phát triển nghề gốm truyền thống địa phương, tiếp nối truyền thống gốm suốt nhiều đời ở Phước Tích và thử nghiệm các phương pháp pha trộn truyền thống với thiết kế mới.",
            "Các nghệ nhân khác trong làng cũng tích cực tham gia các hoạt động giữ lửa lò gốm và giới thiệu gốm đến du khách, giúp nghề gốm Phước Tích có đất sống mới trong thời hiện đại."
          ]
        }
      ]
    },
    {
      "title": "6. Tiềm năng – Văn hoá & xã hội",
      "subsections": [
        {
          "title": "a) Di sản văn hóa",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Phước Tích được công nhận là di tích quốc gia quan trọng thứ hai sau Làng cổ Đường Lâm ở Việt Nam, bởi sự bảo tồn kiến trúc làng quê và nghề gốm lâu đời."
              ]
            }
          ]
        },
        {
          "title": "b) Giá trị lịch sử & nghệ thuật",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Gốm Phước Tích không chỉ là sản phẩm thủ công mà còn chứa đựng giá trị lịch sử – văn hoá suốt 500 năm, từng là vật dụng trong cung đình và đời sống thường nhật. Những lò gốm truyền thống, kiến trúc làng cổ, nhà rường và cảnh quan thiên nhiên tạo nên một di sản tổng thể hấp dẫn khách du lịch và nhà nghiên cứu."
              ]
            }
          ]
        },
        {
          "title": "c) Cơ hội phát triển bền vững",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Kết hợp du lịch làng nghề với các dịch vụ trải nghiệm, nhà ở homestay, ẩm thực truyền thống, và các sản phẩm gốm sáng tạo có thương hiệu có thể đưa làng nghề Phước Tích trở thành điểm đến văn hóa – nghệ thuật nổi bật của miền Trung."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Website Huế Craft Village 4.0"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "🏫 Trung tâm GDNN-GDTX khu vực 2"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Google Sites"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Report abuse"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Page details"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Page updated"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Google Sites"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Report abuse"
              ]
            }
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/gom-phuoc-tich.png",
      "alt": "Nghề làm gốm Phước Tích — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Làng gốm Phước Tích, Phong Điền, Thừa Thiên Huế",
  "youtubeEmbeds": [],
  "villageSlug": "gom-phuoc-tich"
};
export const longCungDinhHueCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Lọng cung đình Huế — Làng nghề Huế",
  "metaDescription": "Nghề làm lọng cung đình Huế: vị trí, lịch sử, quy trình tre lụa và nghệ nhân tiêu biểu.",
  "categoryEyebrow": "Lễ nghi — mỹ nghệ",
  "heroTitle": "Nghề làm lọng cung đình Huế",
  "heroTagline": "Lọng lụa gấm — nét uy nghi của di sản cung đình.",
  "introCardParagraphs": [
    "Nghề làm lọng cung đình Huế gắn với nghi lễ, lễ hội và tín ngưỡng, với khung tre uốn, gen gỗ và vải gấm thêu rồng phượng."
  ],
  "heroImage": "/images/villages/lam-long-cung-dinh-hue.jpg",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm lọng cung đình truyền thống được duy trì tại TP. Huế, tỉnh Thừa Thiên – Huế, đặc biệt ở khu vực Phường Đúc và đường Bùi Thị Xuân. Đây là một trong số rất ít nơi còn giữ được nghề thủ công độc đáo này ở vùng đất cố đô."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm lọng truyền thống có nguồn gốc từ thời đại phong kiến Việt Nam, với tư liệu cho thấy nghề bắt đầu phát triển từ thời kỳ Lê – Mạc, và ông tổ nghề được ghi nhận là Lê Quang Hành. Lọng từng được gọi là dù thần hay dù quan — dùng để che nắng, biểu thị quyền uy, địa vị trong triều đình và quan lại xưa.",
            "Trong thời Nguyễn, lọng là vật dụng quan trọng trong các nghi lễ cung đình và hiện vẫn giữ vai trò trang trọng trong các lễ hội văn hóa cũng như đời sống tín ngưỡng của người dân Huế."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Nguyên liệu chính",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Tre lồ ô được chọn lựa kỹ từ rừng già vì độ bền và đàn hồi."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Gỗ mít dùng làm trung tâm kết cấu (gen)."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Vải lụa hoặc gấm dùng phủ trên khung lọng."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình chính",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Quy trình làm lọng cung đình rất công phu với nhiều bước thủ công:"
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Chuẩn bị và chế biến nguyên liệu: Chẻ, vót, ngâm, phơi, sấy để tre không bị mối mọt."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Gia công khung lọng: Uốn, khoan, tiện, lắp ghép các nan tre và gen gỗ để tạo bộ khung linh hoạt."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Phủ vải và trang trí: Phủ vải gấm, thêu họa tiết rồng phượng, tua rua và các chi tiết nghệ thuật."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Hoàn thiện: Đặt các chi tiết, kiểm tra cân đối, tạo độ chắc chắn và vẻ thẩm mỹ."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Kiểm tra chất lượng: Đảm bảo tính bền, độ linh hoạt và tính nghệ thuật."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Mỗi chiếc lọng là kết quả của hàng chục công đoạn thủ công tinh xảo đòi hỏi sự tỉ mỉ và nghệ thuật cao của người thợ."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Ngày nay, nghề làm lọng cung đình không chỉ phục vụ các nghi lễ truyền thống như rước thần linh, lễ cưới hỏi, đám tang hay lễ hội tín ngưỡng, mà còn được du khách gần xa biết đến và đặt hàng.",
            "Ngoài phục vụ thị trường trong nước, lọng Huế còn được xuất đi nước ngoài — đặc biệt phục vụ cộng đồng người Việt và sự kiện văn hóa ở châu Âu.",
            "Làng nghề cũng có thể kết nối với du lịch trải nghiệm, giáo dục văn hóa và thương mại điện tử, góp phần phát triển kinh tế địa phương trong bối cảnh bảo tồn văn hóa. Việc tăng cường ứng dụng công nghệ thông tin, quảng bá online và liên kết với các lễ hội là hướng đi tiềm năng."
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Một trong những nghệ nhân tiêu biểu nhất của nghề này là ông Hoàng Ngọc Tuyên — chủ cơ sở “Tre mỹ nghệ Ngọc Tuyên” tại TP. Huế.",
            "Ông gắn bó với nghề hơn 30 năm, tìm tòi học hỏi để lưu giữ và phát triển nghề làm lọng cung đình. Ông đã xây dựng và duy trì cơ sở sản xuất với đội ngũ thợ, tạo công ăn việc làm cho lao động địa phương. Sản phẩm của ông đã xuất hiện trong nhiều Festival Huế và các kỳ triển lãm tại các tỉnh thành khác, được du khách đánh giá cao. Năm 2016, ông được phong tặng danh hiệu “Nghệ nhân Ưu tú” vì những đóng góp trong bảo tồn và phát huy giá trị nghề truyền thống."
          ]
        }
      ]
    },
    {
      "title": "6. Ý nghĩa văn hóa – xã hội",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Chiếc lọng cung đình Huế không chỉ là một sản phẩm thủ công mỹ nghệ mà còn là biểu tượng của sự trang trọng, quý phái và tín ngưỡng sâu sắc của người dân cố đô.",
            "Lọng hiện diện trong các nghi lễ quan trọng như cưới hỏi, đón rước thần linh, đám tang, lễ hội cung đình… để tôn vinh sự uy nghiêm và trang trọng của buổi lễ.",
            "Ngoài ra, lọng còn được trưng bày ở chùa, đình làng và nhà thờ họ như biểu tượng văn hóa tín ngưỡng truyền thống.",
            "Lọng Huế còn được ví như một sản phẩm thể hiện nét văn hóa truyền thống đặc sắc, gắn liền với đời sống tâm linh và thẩm mỹ của người xứ Huế."
          ]
        },
        {
          "type": "paragraphs",
          "items": [
            "Website Huế Craft Village 4.0",
            "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí",
            "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi",
            "🏫 Trung tâm GDNN-GDTX khu vực 2",
            "Page updated",
            "Google Sites",
            "Report abuse"
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/lam-long-cung-dinh-hue.jpg",
      "alt": "Nghề làm lọng cung đình Huế — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Phường Đúc, Huế lọng cung đình",
  "youtubeEmbeds": [],
  "villageSlug": "long-cung-dinh-hue"
};
export const quatGiayBaoVinhCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Quạt giấy phố cổ Bao Vinh — Làng nghề Huế",
  "metaDescription": "Nghề làm quạt giấy phố cổ Bao Vinh: lịch sử thương cảng, nguyên liệu tre giấy và quy trình thủ công.",
  "categoryEyebrow": "Thủ công phố cổ",
  "heroTitle": "Nghề làm quạt giấy",
  "heroSubtitle": "Phố cổ Bao Vinh",
  "heroTagline": "Quạt giấy thanh tao bên dòng Hương Giang.",
  "introCardParagraphs": [
    "Nghề làm quạt giấy ở phố cổ Bao Vinh lưu giữ kỹ thuật nan tre, dán áo quạt và họa tiết thư pháp — biểu tượng tinh tế của người Huế."
  ],
  "heroImage": "/images/villages/quat-giay-bao-vinh.jpg",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm quạt giấy truyền thống hiện vẫn được gìn giữ ở Phố cổ Bao Vinh, thuộc Tổ dân phố Bao Vinh, phường Hương Vinh, thành phố Huế – một khu di sản nằm bên dòng sông Hương thơ mộng. Đây là một trong những địa danh văn hóa tiêu biểu của Huế, vốn nổi tiếng với lịch sử lâu đời và các nghề thủ công truyền thống."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Phố cổ Bao Vinh xưa là thương cảng sầm uất từ thời Nhà Nguyễn, nơi diễn ra giao thương nhộn nhịp giữa các thương nhân trong và ngoài nước. Trong bối cảnh này, quạt giấy xuất hiện sớm và trở thành vật dụng phổ biến trong đời sống thường nhật của người dân xứ Huế.",
            "Quạt giấy Bao Vinh mang vẻ đẹp thanh tao, nhẹ nhàng, thể hiện phong cách tinh tế đặc trưng của con người và văn hóa cố đô. Dù trải qua thời gian, nghề làm quạt giấy ở đây vẫn được bảo tồn như một di sản văn hóa sống động, phản ánh nét lịch sử lâu đời và giá trị truyền thống của vùng đất này."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Nguyên liệu chính",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tre:được chọn kỹ, ngâm nước trong thời gian để tránh mối mọt, sau đó được vót, chẻ thành nan mảnh và đều tăm tắp trước khi sử dụng."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Giấy: Truyền thống dùng giấy dó hoặc giấy thủ công, nay còn dùng các loại giấy bền đẹp khác để tăng chất lượng sản phẩm."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình làm quạt",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Chọn nguyên liệu: Lựa chọn tre và giấy phù hợp, xử lý tre để tăng độ bền."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Gia công nan: Nan tre được cắt, vót, đánh nhẵn và cố định bởi đinh ở một đầu. Người thợ phải đảm bảo kích thước đều và không bị thô ráp."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Dán áo quạt: Lớp giấy hoặc vải được dán khéo léo lên từng nan quạt sao cho cân đối, phẳng mịn. Đây là khâu quyết định thẩm mỹ sản phẩm."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Trang trí và hoàn thiện: Người thợ dùng cọ vẽ để trang trí họa tiết như phong cảnh Huế, thư pháp, hoa lá… làm tăng giá trị nghệ thuật cho chiếc quạt."
              ]
            }
          ]
        },
        {
          "title": "c) Giá trị nghệ thuật",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Những họa tiết trên quạt thường gắn với hình ảnh sông Hương, núi Ngự, thư pháp truyền thống, tạo nên sự khác biệt và thẩm mỹ riêng của quạt Bao Vinh."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm quạt giấy ở Phố cổ Bao Vinh có nhiều tiềm năng phát triển trong bối cảnh hiện đại:"
          ]
        }
      ],
      "subsections": [
        {
          "title": "a) Giá trị văn hóa và du lịch",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Quạt không chỉ là vật dụng mà còn trở thành món quà lưu niệm độc đáo cho du khách khi đến Huế, mang theo hơi thở văn hóa cố đô. Phố cổ Bao Vinh là điểm đến hấp dẫn trong các tuyến du lịch văn hóa – lịch sử, nơi khách có thể quan sát và trải nghiệm nghề trực tiếp."
              ]
            }
          ]
        },
        {
          "title": "b) Đổi mới sản phẩm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Các nghệ nhân đã sáng tạo ra nhiều loại quạt mới như quạt tranh, quạt trang trí, quạt thư pháp, đáp ứng nhu cầu thị trường hiện đại, không chỉ dùng để quạt mà còn để trưng bày, làm quà tặng. Một số sản phẩm còn được xuất khẩu ra nước ngoài, giúp quảng bá văn hóa Huế toàn cầu."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Mặc dù hầu hết các nguồn không chỉ đích danh nhiều nghệ nhân, nhưng bài viết giới thiệu thợ làm quạt tại Phố cổ Bao Vinh là chị Nguyễn Thị Lộc – một người thợ say mê với nghề, luôn giữ gìn kỹ thuật thủ công và truyền lại cho thế hệ sau trong cộng đồng địa phương.",
            "Ngoài ra, nhiều gia đình làm nghề lâu đời tại Phố cổ Bao Vinh không ngừng truyền dạy nghề làm quạt giấy, góp phần giữ cho nghề truyền thống này còn tồn tại đến ngày nay."
          ]
        }
      ]
    },
    {
      "title": "6. Tiềm năng – Nghệ thuật và bản sắc văn hóa",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm quạt giấy ở Phố cổ Bao Vinh không chỉ là sản xuất thủ công mà còn là biểu tượng của văn hóa Huế. Quạt giấy phản ánh tính cách dịu dàng, thanh lịch, tinh tế của con người xứ Huế; họa tiết thường lấy cảm hứng từ cảnh đẹp, âm nhạc cung đình hay phong cảnh miền Trung, làm tăng chiều sâu nghệ thuật cho sản phẩm.",
            "Trong đời sống văn hóa – nghệ thuật truyền thống, quạt giấy Bao Vinh từng là phụ kiện không thể thiếu trong các điệu múa cung đình, lễ hội Áo dài, và các hoạt động biểu diễn Nhã nhạc cung đình Huế, góp phần làm nên nền văn hóa độc đáo được UNESCO công nhận.",
            "Ngày nay, quạt giấy Bao Vinh là kết tinh của nghệ thuật và văn hoá Huế, được du khách trong nước và quốc tế yêu thích không chỉ vì công năng mà còn vì giá trị thẩm mỹ và hơi thở lịch sử truyền thống, tạo nên trải nghiệm văn hóa sâu sắc khi đến thăm Huế.",
            "Website Huế Craft Village 4.0",
            "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí",
            "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi",
            "🏫 Trung tâm GDNN-GDTX khu vực 2",
            "Google Sites",
            "Report abuse",
            "Page details",
            "Page updated",
            "Google Sites",
            "Report abuse"
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/quat-giay-bao-vinh.jpg",
      "alt": "Nghề làm quạt giấy — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Phố cổ Bao Vinh, Hương Vinh, Huế",
  "youtubeEmbeds": [],
  "villageSlug": "quat-giay-bao-vinh"
};
export const langHuongThuyXuanCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Làng hương trầm Thủy Xuân — Làng nghề Huế",
  "metaDescription": "Làng hương Thủy Xuân: vị trí, lịch sử, quy trình làm hương, tiềm năng du lịch và văn hóa.",
  "categoryEyebrow": "Hương truyền thống",
  "heroTitle": "Làng hương trầm Thủy Xuân",
  "heroTagline": "Sắc hương cổ kính nhuộm tím ký ức đất Cố đô.",
  "introCardParagraphs": [
    "Nghề làm hương ở Thủy Xuân lưu giữ kỹ thuật pha trầm, se hương và phối sắc thủ công, tạo nên không gian tâm linh đậm chất Huế."
  ],
  "heroImage": "/images/villages/huong_tram_thuy_xuan.jpg",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Làng hương trầm Thủy Xuân nằm ở phường Thủy Xuân, thành phố Huế, cách trung tâm thành phố khoảng 7 km về hướng Tây Nam, trên tuyến đường Huyền Trân Công Chúa, gần các điểm du lịch như đồi Vọng Cảnh và lăng Tự Đức. Đây là một làng nghề truyền thống nổi tiếng và được nhiều du khách ghé thăm khi đến Huế."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Nghề làm hương trầm ở làng Thủy Xuân đã có lịch sử hơn 700 năm, bắt nguồn từ thời Nhà Nguyễn, khi làng chuyên sản xuất hương để phục vụ cung đình, các quan lại và người dân địa phương ở khu vực Thuận Hóa – Phú Xuân (ngày nay là Thừa Thiên – Huế). Qua nhiều thế hệ, nghề này được người dân giữ gìn và truyền dạy từ cha ông đến con cháu, trở thành một phần của đời sống văn hóa – tâm linh địa phương."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Nguyên liệu chính",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Tăm hương: Được làm từ ruột tre già được chọn lựa kỹ, chẻ nhỏ và phơi nắng nhiều ngày để khi đốt không bị gãy và cháy đều."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Bột trầm và hương liệu: Trầm và nhiều loại nguyên liệu tự nhiên như quế, hồi, thảo quả, bạch chỉ, hắc hương, cùng với vỏ quả bưởi khô – chất kết dính tự nhiên được trộn với nước để tạo thành hỗn hợp dẻo."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình sản xuất",
          "blocks": [
            {
              "type": "bullets",
              "items": [
                "Chuẩn bị nguyên liệu: Nguyên liệu thơm được xay thành bột mịn, tre được phơi nắng cho khô giòn."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Pha trộn bột trầm: Bột trầm cùng các nguyên liệu thảo mộc được trộn với chất kết dính sao cho đạt độ dẻo quánh."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Se hương: Đây là công đoạn cầu kỳ nhất – người thợ se hương bằng tay để que hương có độ đều, độ thơm và độ cháy ổn định."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Phơi và hoàn thiện: Que hương sau khi se xong sẽ được phơi trực tiếp dưới nắng cho khô và giữ được mùi thơm lâu."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Sản phẩm thường đa dạng về hương thơm như quế, sả, nhài…, nhưng hương trầm agarwood (trầm) vẫn là loại tạo nên danh tiếng cho làng nghề Thủy Xuân với mùi thơm thanh tao và đặc trưng."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "subsections": [
        {
          "title": "a) Du lịch – trải nghiệm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Làng hương Thủy Xuân hiện là điểm đến du lịch nổi bật ở Huế, thu hút khách trong và ngoài nước không chỉ để mua hương mà còn tham quan quy trình sản xuất, chụp ảnh check-in với những bó hương đủ màu rực rỡ phơi trên đường làng – cảnh tượng rất đặc trưng."
              ]
            }
          ]
        },
        {
          "title": "b) Thương mại & thị trường",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Sản phẩm hương Thủy Xuân không chỉ phục vụ nhu cầu tâm linh trong tỉnh mà còn được phân phối đến các thành phố lớn như Hà Nội, TP. Hồ Chí Minh, Đà Nẵng, và một số sản phẩm còn xuất khẩu ra nước ngoài. Hương dùng nguyên liệu tự nhiên, không độc hại, được đánh giá có mùi thơm tao nhã, phù hợp cả phục vụ thư giãn tinh thần ngoài nhu cầu thờ cúng."
              ]
            }
          ]
        },
        {
          "title": "c) Du lịch cộng đồng gắn nghề",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Nhiều hộ dân hiện kết hợp làm hương và phục vụ du lịch, như cho khách trải nghiệm tự tay làm hương, thuê trang phục truyền thống để chụp ảnh, hoặc mua quà lưu niệm, tạo thêm nguồn thu cho cộng đồng địa phương."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Mặc dù không có nhiều tài liệu trực tuyến liệt kê cụ thể các nghệ nhân, các nguồn tin nhắc đến nghệ nhân và gia đình lâu năm gắn bó với nghề như những người thợ truyền thống duy trì công thức và kỹ thuật làm hương suốt nhiều thế hệ. Điều này thể hiện vai trò quan trọng của các nghệ nhân địa phương trong giữ gìn nghề."
          ]
        }
      ]
    },
    {
      "title": "6. Tiềm năng: Văn hóa – xã hội – tâm linh",
      "subsections": [
        {
          "title": "a) Giá trị văn hóa & tâm linh",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Nghề làm hương gắn liền với đời sống tâm linh của người Việt nói chung và người Huế nói riêng – hương được dùng trong các dịp Tết, lễ, cúng gia tiên và gắn với niềm tin, lễ nghi truyền thống."
              ]
            }
          ]
        },
        {
          "title": "b) Biểu tượng du lịch & điểm check-in",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Những bó hương đủ màu sắc trải dài hai bên đường là hình ảnh rất nổi tiếng, khiến Thủy Xuân trở thành “xứ trầm thơm”, tạo ấn tượng đẹp với du khách và góp phần quảng bá văn hóa Huế."
              ]
            }
          ]
        },
        {
          "title": "c) Lợi ích sức khỏe & thư giãn",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Một số loại hương ở đây được dùng như liệu pháp thư giãn, giúp giảm stress và mang lại cảm giác dễ chịu, bên cạnh mục đích thờ cúng truyền thống."
              ]
            }
          ]
        },
        {
          "title": "d) Riêng biệt với các làng hương khác",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Làng hương Thủy Xuân nổi bật bởi công thức gia truyền và mùi thơm đặc trưng, không dùng hóa chất độc hại, tạo nên sản phẩm có giá trị văn hóa và thương mại đặc sắc."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Website Huế Craft Village 4.0"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "🏫 Trung tâm GDNN-GDTX khu vực 2"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Google Sites"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Report abuse"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Page details"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Page updated"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Google Sites"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Report abuse"
              ]
            }
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/huong_tram_thuy_xuan.jpg",
      "alt": "Làng hương trầm Thủy Xuân — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Làng hương Thủy Xuân, phường Thủy Xuân, Huế",
  "youtubeEmbeds": [],
  "villageSlug": "lang-huong-thuy-xuan"
};
export const tranhLangSinhCraftBundle: import("@/data/google-sites-crafts/types").GoogleSitesCraftBundle = {
  "pageTitle": "Tranh làng Sình — Làng nghề Huế",
  "metaDescription": "Tranh làng Sình: tranh mộc bản, lịch sử, quy trình in và tô màu điệp, tiềm năng du lịch.",
  "categoryEyebrow": "Tranh dân gian",
  "heroTitle": "Tranh làng Sình",
  "heroTagline": "Dòng tranh mộc bản đặc sắc gắn tín ngưỡng xứ Huế.",
  "introCardParagraphs": [
    "Tranh làng Sình (Lại Ân) là nghệ thuật in mộc bản với màu điệp tự nhiên, phục vụ lễ cúng, cầu an và đời sống văn hóa dân gian cố đô."
  ],
  "heroImage": "/images/villages/tranh-lang-sinh.png",
  "sections": [
    {
      "title": "1. Vị trí",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Làng Sình hay còn gọi là làng Lại Ân, thuộc thôn Lại Ân, xã Phú Mậu, huyện Phú Vang, tỉnh Thừa Thiên – Huế. Làng nằm ven sông Hương, đối diện cảng Thanh Hà – một thương cảng sầm uất thời các chúa ở Đàng Trong, và gần khu vực thành phố Huế ngày nay. Đây là một làng văn vật với lịch sử phát triển lâu đời, không chỉ nổi tiếng về tranh mộc bản mà còn cả lễ hội vật truyền thống."
          ]
        }
      ]
    },
    {
      "title": "2. Lịch sử",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Tranh làng Sình có lịch sử hơn 400 năm, được xem là một nghệ thuật tranh dân gian đặc sắc của miền Trung, hình thành sau khi làng được định cư và dân di cư từ miền Bắc mang nghề in tranh gỗ đến đây. Tranh chịu ảnh hưởng của tranh Đông Hồ nhưng phát triển theo xu hướng phục vụ tín ngưỡng – dùng trong các lễ cầu an, giải hạn, thờ cúng tổ tiên.",
            "Qua thời gian, tranh Sình từng bị mai một, nhiều bản mộc bị thất lạc do chiến tranh và sự thay đổi thờ cúng, nhưng gần đây làng đã hồi sinh nghề truyền thống này."
          ]
        }
      ]
    },
    {
      "title": "3. Sản phẩm (quy trình làm)",
      "subsections": [
        {
          "title": "a) Sản phẩm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tranh làng Sình là tranh mộc bản in gỗ, chủ yếu dùng trong lễ nghi tâm linh như thờ cúng, lễ Tết và các nghi thức truyền thống Huế. Tranh còn có các đề tài trang trí và đời sống hiện nay."
              ]
            }
          ]
        },
        {
          "title": "b) Quy trình sản xuất",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Theo các nguồn tham khảo, tranh Sình được làm thủ công qua nhiều bước:"
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Chuẩn bị giấy và bột điệp: Giấy thường được xử lý bằng bột vỏ sò từ Tam Giang trước khi in để tạo độ bền và độ sáng."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Khắc mộc bản: Nghệ nhân dùng gỗ mít hoặc gỗ trái cây để khắc hình vẽ lên bản gỗ làm mộc bản in."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "In tranh: Dùng mực tự nhiên (đen) trải đều lên mộc bản rồi ép giấy lên."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Phơi khô: Bức tranh sau khi in sẽ được phơi để cố định mực."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Phối màu: Tranh sau khi phơi được tô bằng màu tự nhiên từ lá, vỏ cây, tro, vỏ điệp… dùng bút làm từ rễ cây."
              ]
            },
            {
              "type": "bullets",
              "items": [
                "Hoàn thiện: Bức tranh hoàn chỉnh sẽ lấp lánh màu và phản ánh nét tâm linh văn hóa Huế."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Nhiều sản phẩm tranh hiện đại cũng có các chủ đề trang trí ngoài tín ngưỡng để phục vụ nhu cầu du lịch."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "4. Tiềm năng phát triển",
      "subsections": [
        {
          "title": "a) Bảo tồn văn hóa truyền thống",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tranh làng Sình là một dòng tranh dân gian độc đáo mang bản sắc văn hóa xứ Huế, thể hiện niềm tin tâm linh, đời sống tinh thần người dân vùng Cố đô."
              ]
            }
          ]
        },
        {
          "title": "b) Du lịch trải nghiệm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Sự phục hồi nghề, cùng với việc kết hợp du lịch cộng đồng – trải nghiệm làm tranh, giúp thu hút du khách trong và ngoài nước đến tham quan, trải nghiệm quá trình làm tranh dân gian và tìm hiểu lịch sử."
              ]
            }
          ]
        },
        {
          "title": "c) Giá trị nghệ thuật và thương mại",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tranh Sình từng được so sánh ngang với tranh Đông Hồ (Bắc Ninh) và đã bắt đầu được biến tấu phục vụ trang trí và lưu niệm cho du khách, góp phần tạo thêm thu nhập cho người làm nghề."
              ]
            }
          ]
        }
      ]
    },
    {
      "title": "5. Nghệ nhân tiêu biểu",
      "blocks": [
        {
          "type": "paragraphs",
          "items": [
            "Một trong những nghệ nhân nổi bật nhất trong việc gìn giữ, khôi phục và truyền nghề tranh làng Sình là nghệ nhân Kỳ Hữu Phước – người thuộc thế hệ kế thừa lâu đời trong dòng tranh này. Ông đã dành nhiều năm thu thập, giữ gìn và khôi phục các khuôn mộc bản cổ, thậm chí bảo vệ và chôn giữ một số bản khắc xưa trong giai đoạn tranh gặp khó khăn; đồng thời tích cực truyền nghề cho thế hệ trẻ và mở lớp đào tạo để duy trì nghề truyền thống."
          ]
        }
      ]
    },
    {
      "title": "6. Tiềm năng – Ý nghĩa văn hoá & xã hội",
      "subsections": [
        {
          "title": "a) Di sản văn hóa dân gian",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tranh làng Sình không chỉ là sản phẩm thủ công, mà còn là bằng chứng của đời sống tâm linh và tín ngưỡng của cư dân Huế qua nhiều thế kỷ, đóng vai trò trong các lễ cúng tổ tiên, cầu an, và các dịp lễ Tết. Những hình ảnh trong tranh thường mang tính biểu tượng sâu sắc."
              ]
            }
          ]
        },
        {
          "title": "b) Giá trị nghệ thuật độc đáo",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Tranh Sình sử dụng màu tự nhiên và kỹ thuật in mộc bản thủ công, với sắc màu chân phương nhưng biểu cảm, khác biệt với tranh phương Bắc và góp phần phong phú cho dòng tranh dân gian Việt Nam."
              ]
            }
          ]
        },
        {
          "title": "c) Hồi sinh và phát triển",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Nhờ nỗ lực bảo tồn, tranh làng Sình đang được quảng bá thông qua du lịch văn hóa, trải nghiệm nghệ thuật và đào tạo nghề, giúp tạo việc làm và thu nhập cho người dân địa phương."
              ]
            }
          ]
        },
        {
          "title": "d) Giá trị du lịch – trải nghiệm",
          "blocks": [
            {
              "type": "paragraphs",
              "items": [
                "Du khách ngày nay không chỉ đến để mua tranh mà còn tham gia trải nghiệm tự tay in, tô màu, tìm hiểu lịch sử và văn hóa Huế qua tranh dân gian – đây là một điểm nhấn du lịch độc đáo của vùng cố đô."
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Website Huế Craft Village 4.0"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "👨‍🏫 Xây dựng nội dung: Học sinh: Đinh Thị Bảo Xuyến - Lê Trọng Trí"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Giáo viên hướng dẫn: Trần Hữu Phong - Đoàn Thị Mai Chi"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "🏫 Trung tâm GDNN-GDTX khu vực 2"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Page updated"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Google Sites"
              ]
            },
            {
              "type": "paragraphs",
              "items": [
                "Report abuse"
              ]
            }
          ]
        }
      ]
    }
  ],
  "galleryFromSource": [
    {
      "src": "/images/villages/tranh-lang-sinh.png",
      "alt": "Tranh làng Sình — ảnh đại diện (chưa lưu được bộ ảnh Sites vào repo; xem scripts/craft-gallery-images.txt)"
    }
  ],
  "mapSearchQuery": "Làng Sình Lại Ân, Phú Mậu, Huế",
  "youtubeEmbeds": [],
  "villageSlug": "tranh-lang-sinh"
};
